%% Clear Window...
clc;
clear all;
close all;

%% Global variables...
globalVars();

%% Load dataSet Data...
dataSetNum = 2;
[trainData, testData, classNum] = loadData(dataSetNum);

%% Training...
[Lambda_1, Alpha, Beta, ...
    Lambda_2, Mu, Rho] = trainPath(trainData, classNum);

%% Validation...
[optLambda_1, optAlpha, optBeta, ...
    optLambda_2, optMu, optRho] = validPath(...
    trainData, trainData, classNum, ...
    Lambda_1, Alpha, Beta, ...
    Lambda_2, Mu, Rho);

%% Test..
corrPred = testPath(trainData, testData, classNum,...
    optLambda_1, optAlpha, optBeta, ...
    optLambda_2, optMu, optRho);

%% OVOVR TSVM...

