%% Clear Window...
clc;
clear all;
close all;

%% Global variables...
globalVars();

%% Load dataSet Data...
dataSetNum = 2;
[trainData, testData, classNum] = loadData(dataSetNum);

tic;
%% OVOVR TSVM Training...
[QPPLambda_1, QPPAlpha, QPPBeta, ...
    QPPLambda_2, QPPMu, QPPRho] = multiTSVM(trainData, testData, ...
    classNum, lambda_one, lambda_two);
time = toc

%% Test..
corrPred = testPath(trainData, testData, classNum,...
    QPPLambda_1, QPPAlpha, QPPBeta, ...
    QPPLambda_2, QPPMu, QPPRho);